=== PRTG/JMXMiniProbe/profiles/Profile.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="profiles">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="profile" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="kind" minOccurs="1">
				<xs:annotation>
					<xs:documentation>Unique Identifier for the sensor(should start with 'mjjmx*'")</xs:documentation>
				</xs:annotation>
			   </xs:element>
              <xs:element type="xs:string" name="name" minOccurs="1">
				<xs:annotation>
					<xs:documentation>Name of the sensor. Will become the default name</xs:documentation>
				</xs:annotation>
			   </xs:element>
              <xs:element type="xs:string" name="tag" minOccurs="1">
				<xs:annotation>
					<xs:documentation>Tags values. Should include the tag of the parrent</xs:documentation>
				</xs:annotation>
			   </xs:element>
              <xs:element type="xs:string" name="description" minOccurs="0">
				<xs:annotation>
					<xs:documentation>What is displayed in the description in the Add Sensor Dialog</xs:documentation>
				</xs:annotation>
			   </xs:element>
              <!--xs:element type="xs:string" name="baseclass" minOccurs="1"/-->
			  <xs:element name="baseclass" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>The class that implements the sensor used</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
				  <xs:restriction base="xs:string">
					<!-- Tags: jmxsensor,mjjmxsensor -->
					<xs:enumeration value="com.paessler.prtg.jmx.sensors.JMXSensor"/>
					<!-- Tags: jmxsensor,mjjmxsensor -->
					<xs:enumeration value="com.paessler.prtg.jmx.sensors.port.PortSensor"/>
				  </xs:restriction>
				</xs:simpleType>
			  </xs:element>
              <xs:element type="xs:string" name="help"/>
              <!-- Properties -->
			  <xs:element name="properties" minOccurs="0">
				<xs:complexType>
				  <xs:sequence>
					<xs:element name="property" type="PropertyType"/>
				  </xs:sequence>
				</xs:complexType>
			  </xs:element>
              <!-- Properties -->
              <!-- Please note, the total number of Attributes for all the entries in a Profile, 
			  is limited to PRTG Channels per Sensor -->
              <xs:element name="entries">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="entry">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="object" minOccurs="1">
							<xs:annotation>
								<xs:documentation>Name of Entry</xs:documentation>
							</xs:annotation>
						  </xs:element>
                          <xs:element type="xs:string" name="displayvalue" minOccurs="0">
							<xs:annotation>
								<xs:documentation>Value to be displayed</xs:documentation>
							</xs:annotation>
						  </xs:element>
                          <xs:element type="xs:string" name="description" minOccurs="0">
							<xs:annotation>
								<xs:documentation>Description of entry</xs:documentation>
							</xs:annotation>
						  </xs:element>
                          <xs:element type="xs:string" name="shortdescription" minOccurs="0">
							<xs:annotation>
								<xs:documentation>Short description, will be used to indicate entry for a Channel</xs:documentation>
							</xs:annotation>
						  </xs:element>
                          <xs:element type="xs:string" name="comment" minOccurs="0">
							<xs:annotation>
								<xs:documentation>Arbitrary comment</xs:documentation>
							</xs:annotation>
						  </xs:element>
              			<!-- Properties -->
						<xs:element name="properties" minOccurs="0">
							<xs:complexType>
							  <xs:sequence>
								<xs:element name="property" type="PropertyType"/>
							  </xs:sequence>
							</xs:complexType>
						</xs:element>
              			<!-- Properties -->
                          <xs:element name="attributes" minOccurs="1" maxOccurs="50">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="attribute">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element type="xs:string" name="object" minOccurs="1"/>
                                      <xs:element type="xs:string" name="displayvalue" minOccurs="0"/>
                                      <xs:element type="xs:string" name="description" minOccurs="0"/>
                                      <xs:element type="xs:string" name="shortdescription" minOccurs="0"/>
                                      <xs:element type="xs:string" name="comment" minOccurs="0"/>
                                      <xs:element name="unit" minOccurs="1">
										<xs:annotation>
											<xs:documentation>Valid Units for PRTG</xs:documentation>
										</xs:annotation>
								        <xs:simpleType>
								          <xs:restriction base="xs:string">
										    <xs:enumeration value="BANDWIDTH"/>		<!-- BytesBandwidth -->
										    <xs:enumeration value="MEMORY"/>		<!-- BytesMemory -->
										    <xs:enumeration value="DISK"/>			<!-- BytesDisk -->
										    <xs:enumeration value="FILE"/>			<!-- BytesFile -->
										    <xs:enumeration value="TIME_RESPONSE"/>	<!-- TimeResponse[ms] -->
										    <xs:enumeration value="TIME_SECONDS"/>	<!-- TimeSeconds -->
										    <xs:enumeration value="TIME_HOURS"/>	<!-- TimeHours -->
										    <xs:enumeration value="TEMP"/>			<!-- Temperature -->
										    <xs:enumeration value="PERCENT"/>		<!-- Percent -->
										    <xs:enumeration value="COUNT"/>			<!-- Count -->
										    <xs:enumeration value="CPU"/>  			<!-- CPU (*) -->
										    <xs:enumeration value="CUSTOM"/>		<!-- Custom (define the name of the unit using the additional field customunit) -->
								          </xs:restriction>
								        </xs:simpleType>
                                      </xs:element>
                                      <xs:element type="xs:string" name="customunit" minOccurs="0"/>
                                      <xs:element type="xs:boolean" name="enabled" minOccurs="0"/>
                                      <xs:element type="xs:float" name="mpy" default="1.0" minOccurs="0"/>
                                      <xs:element type="xs:float" name="div" default="1.0" minOccurs="0"/>
                                      <xs:element type="xs:int" name="limitmaxerror" minOccurs="0"/>
                                      <xs:element type="xs:int" name="limitmaxwarning" minOccurs="0"/>
                                      <xs:element type="xs:int" name="limitminwarning" minOccurs="0"/>
                                      <xs:element type="xs:int" name="limitminerror" minOccurs="0"/>
                                      <xs:element type="xs:string" name="limiterrormsg" minOccurs="0"/>
                                      <xs:element type="xs:string" name="limitwarningmsg" minOccurs="0"/>
                                      <xs:element type="xs:int" name="limitmode" default="0" minOccurs="0"/>
                                      <xs:element name="properties" minOccurs="0">
                                        <xs:complexType>
                                          <xs:sequence>
											<xs:element name="property" type="PropertyType"/>
                                          </xs:sequence>
                                        </xs:complexType>
                                      </xs:element>
                                      <!-- Properties -->
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <!-- Attribute -->
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <!-- Attributes -->
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <!-- Element -->
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <!-- Profile -->
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- Profiles -->
  
	<!-- Name Value Pairs-->
    <xs:complexType name="NameValuePairsType">
		<xs:annotation>
			<xs:documentation>Arbitrary name value pair</xs:documentation>
		</xs:annotation>
		<xs:sequence>
		  <xs:element type="xs:string" name="name">
			<xs:annotation>
				<xs:documentation>Property name</xs:documentation>
			</xs:annotation>
		   </xs:element>
		  <xs:element type="xs:string" name="value">
			<xs:annotation>
				<xs:documentation>Property value</xs:documentation>
			</xs:annotation>
		   </xs:element>
		</xs:sequence>
	</xs:complexType>
	<!-- Name Value Pairs-->
	<!-- Property-->
    <xs:complexType name="PropertyType">
		<xs:annotation>
			<xs:documentation>Sequence of name value pair</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="property" type="NameValuePairsType"/>
		</xs:sequence>
	</xs:complexType>
	

<!--
                          <xs:element name="properties">
                            <xs:complexType>
                              <xs:sequence>
								<xs:element name="property">
									<xs:annotation>
										<xs:documentation>Arbitrary attribute to be set on the sensor</xs:documentation>
									</xs:annotation>
								  <xs:complexType>
									<xs:sequence>
									  <xs:element type="xs:string" name="name">
										<xs:annotation>
											<xs:documentation>Property name</xs:documentation>
										</xs:annotation>
									   </xs:element>
									  <xs:element type="xs:string" name="value">
										<xs:annotation>
											<xs:documentation>Property value</xs:documentation>
										</xs:annotation>
									   </xs:element>
									</xs:sequence>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
 -->	
</xs:schema>

=== PRTG/JMXMiniProbe/profiles/SensorProfiles.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- ###########################################################
Unit Values[BANDWIDTH, MEMORY, DISK, FILE, TIME_RESPONSE, TIME_SECONDS, TIME_HOURS, TEMP, PERCENT, COUNT,CPU,CUSTOM]
***************************************************************
Please note, the apache.commons.digester3 is * VERY * case sensitive
########################################################### -->
<profiles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Profile.xsd">
	<profile>
		<kind>jmxdosstr</kind>
		<name>JMX OS Strategic</name>
		<tag>mjjmxdosstr,mjmxsensor</tag>
		<description>Strategic OS Sensor</description>
		<baseclass>com.paessler.prtg.jmx.sensors.JMXSensor</baseclass>
		<help>Strategic Host/Operating information CPU Load, Free Mem Disk</help>
		<entries>
			<entry>
				<object>java.lang:type=OperatingSystem</object>
				<description>Operating system metrics</description>
				<shortdescription>OS</shortdescription>
				<attributes>
					<attribute>
						<object>SystemCpuLoad</object>
						<description>SystemCpuLoad</description>
						<unit>CPU</unit>
						<mpy>100.0</mpy>
						<div>1.0</div>
					</attribute>
					<attribute>
						<object>ProcessCpuLoad</object>
						<description>ProcessCpuLoad</description>
						<unit>CPU</unit>
						<mpy>100.0</mpy>
						<div>1.0</div>
					</attribute>
					<attribute>
						<object>FreePhysicalMemorySize</object>
						<description>FreePhysicalMemorySize</description>
						<unit>MEMORY</unit>
					</attribute>
					<attribute>
						<object>AvailableProcessors</object>
						<description>AvailableProcessors</description>
						<unit>COUNT</unit>
					</attribute>
				</attributes>
			</entry>
			<entry>
				<object>java.lang:type=Memory</object>
				<description>Memory Metrics</description>
				<shortdescription>JVM</shortdescription>
				<attributes>
					<attribute>
						<object>NonHeapMemoryUsage</object>
						<description>Initialized heap memory</description>
						<unit>MEMORY</unit>
					</attribute>
					<attribute>
						<object>HeapMemoryUsage</object>
						<description>Committed heap memory</description>
						<unit>MEMORY</unit>
					</attribute>
				</attributes>
			</entry>
			<entry>
				<object>java.lang:type=Threading</object>
				<description>Threading Metrics</description>
				<shortdescription>JVM</shortdescription>
				<attributes>
					<attribute>
						<object>ThreadCount</object>
						<description>Live threads</description>
						<unit>COUNT</unit>
					</attribute>
					<attribute>
						<object>PeakThreadCount</object>
						<description>Peak threads</description>
						<unit>COUNT</unit>
					</attribute>
					<attribute>
						<object>DaemonThreadCount</object>
						<description>Daemon threads</description>
						<unit>COUNT</unit>
					</attribute>
					<attribute>
						<object>TotalStartedThreadCount</object>
						<description>Total threads started</description>
						<unit>COUNT</unit>
					</attribute>
				</attributes>
			</entry>
		</entries>
	</profile>
	<profile>
		<kind>jmxdosinf</kind>
		<name>JMX Host OS Info</name>
		<tag>mjmxsensor,mjjmxdosinf</tag>
		<description>Host OS Metrics</description>
		<baseclass>com.paessler.prtg.jmx.sensors.JMXSensor</baseclass>
		<help>Operating system information from Host, CPU/Mem/Disk</help>
		<entries>
	      <entry>
	        <!--class>com.sun.management.OperatingSystem<class-->
	        <object>java.lang:type=OperatingSystem</object>
	        <description>Information on the management interface of the MBean</description>
	        <shortdescription>OS</shortdescription>
	        <attributes>
	          <attribute>
	            <object>CommittedVirtualMemorySize</object>
	            <description/>
	            <shortdescription>CommittedVirtualMemorySize</shortdescription>
	            <!--type>long</type>
	            <mpy>1.0</mpy>
	            <div>1.0</div-->
	            <unit>MEMORY</unit>
	          </attribute>
	          <attribute>
	            <object>FreePhysicalMemorySize</object>
	            <description/>
	            <shortdescription>FreePhysicalMemorySize</shortdescription>
	            <unit>MEMORY</unit>
	          </attribute>
	          <attribute>
	            <object>FreeSwapSpaceSize</object>
	            <description/>
	            <shortdescription>FreeSwapSpaceSize</shortdescription>
	            <unit>MEMORY</unit>
	          </attribute>
	          <attribute>
	            <object>ProcessCpuLoad</object>
	            <description/>
	            <shortdescription>ProcessCpuLoad</shortdescription>
	            <unit>CPU</unit>
	          </attribute>
	          <attribute>
	            <object>ProcessCpuTime</object>
	            <description/>
	            <shortdescription>ProcessCpuTime</shortdescription>
	            <unit>CPU</unit>
	          </attribute>
	          <attribute>
	            <object>SystemCpuLoad</object>
	            <description/>
	            <shortdescription>SystemCpuLoad</shortdescription>
	            <unit>CPU</unit>
	          </attribute>
	          <attribute>
	            <object>TotalPhysicalMemorySize</object>
	            <description/>
	            <shortdescription>TotalPhysicalMemorySize</shortdescription>
	            <unit>MEMORY</unit>
	          </attribute>
	          <attribute>
	            <object>TotalSwapSpaceSize</object>
	            <description/>
	            <shortdescription>TotalSwapSpaceSize</shortdescription>
	            <unit>MEMORY</unit>
	          </attribute>
	          <attribute>
	            <object>AvailableProcessors</object>
	            <description/>
	            <shortdescription>AvailableProcessors</shortdescription>
	            <unit>COUNT</unit>
	          </attribute>
	          <attribute>
	            <object>SystemLoadAverage</object>
	            <description/>
	            <shortdescription>SystemLoadAverage</shortdescription>
	            <unit>CPU</unit>
	          </attribute>
	          <!--attribute>
	            <object>Arch</object>
	            <description/>
	            <shortdescription>Arch</shortdescription>
	            <unit>String</unit>
	          </attribute-->
	          <!--attribute>
	            <object>Name</object>
	            <description/>
	            <shortdescription>Name</shortdescription>
	            <unit>String</unit>
	          </attribute-->
	          <!--attribute>
	            <object>Version</object>
	            <description/>
	            <shortdescription>Version</shortdescription>
	            <unit>String</unit>
	          </attribute-->
	          <!--attribute>
	            <object>ObjectName</object>
	            <description/>
	            <shortdescription>ObjectName</shortdescription>
	            <unit>String</unit>
	          </attribute-->
	        </attributes>
		  </entry>
		</entries>
	</profile>
</profiles>

=== PRTG/JMXMiniProbe/profiles/JVMGCProfiles.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- ###########################################################
Unit Values[BANDWIDTH, MEMORY, DISK, FILE, TIME_RESPONSE, TIME_SECONDS, TIME_HOURS, TEMP, PERCENT, COUNT,CPU,CUSTOM]
***************************************************************
Please note, the apache.commons.digester3 is * VERY * case sensitive
########################################################### -->
<profiles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Profile.xsd">
	<profile>
		<name>JVM GC Stats MarkSweep</name>
		<tag>jmxsensor,mjjmxsensor</tag>
		<kind>mjjmxgcmssensor</kind>
		<description>Garbage Collection statistics</description>
		<baseclass>com.paessler.prtg.jmx.sensors.JMXSensor</baseclass>
		<help>JVM Mark and Sweep Garbage Collection metrics</help>
		<entries>
			<entry>
				<object>java.lang:type=GarbageCollector,name=PS MarkSweep</object>
				<displayvalue>MS GarbageCollector Stats</displayvalue>
				<description>Mark and Sweap Garbage Collector</description>
				<shortdescription>GC-MS</shortdescription>
				<comment>Class Name:sun.management.GarbageCollectorImpl</comment>
				<attributes>
					<attribute>
						<object>CollectionCount</object>
						<displayvalue/>
						<description>CollectionCount</description>
						<shortdescription/>
						<comment>type=long,unit=COUNT; Value=0</comment>
						<unit/>
						<customunit/>
						<enabled>true</enabled>
					</attribute>
					<attribute>
						<object>CollectionTime</object>
						<displayvalue/>
						<description>CollectionTime</description>
						<shortdescription/>
						<comment>type=long,unit=COUNT; Value=0</comment>
						<unit/>
						<customunit/>
						<enabled>true</enabled>
					</attribute>
					<attribute>
						<object>LastGcInfo</object>
						<displayvalue/>
						<description>LastGcInfo</description>
						<shortdescription/>
						<comment>type=javax.management.openmbean.CompositeData,unit=COUNT</comment>
						<unit/>
						<customunit/>
						<enabled>true</enabled>
					</attribute>
					<attribute>
						<object>MemoryPoolNames</object>
						<displayvalue/>
						<description>MemoryPoolNames</description>
						<shortdescription/>
						<comment>type=[Ljava.lang.String;,unit=COUNT; Value=[Ljava.lang.String;@7c18d288</comment>
						<unit/>
						<customunit/>
						<enabled>true</enabled>
					</attribute>
					<attribute>
						<object>Name</object>
						<displayvalue/>
						<description>Name</description>
						<shortdescription/>
						<comment>type=java.lang.String,unit=COUNT; Value=PS MarkSweep</comment>
						<unit/>
						<customunit/>
						<enabled>true</enabled>
					</attribute>
					<attribute>
						<object>ObjectName</object>
						<displayvalue/>
						<description>ObjectName</description>
						<shortdescription/>
						<comment>type=javax.management.ObjectName,unit=COUNT; Value=java.lang:type=GarbageCollector,name=PS MarkSweep</comment>
						<unit/>
						<customunit/>
						<enabled>true</enabled>
					</attribute>
					<attribute>
						<object>Valid</object>
						<displayvalue/>
						<description>Valid</description>
						<shortdescription/>
						<comment>type=boolean,unit=COUNT; Value=true</comment>
						<unit/>
						<customunit/>
						<enabled>true</enabled>
					</attribute>
				</attributes>
			</entry>
		</entries>
	</profile>
	<profile>
		<name>JVM GC Stats PS Scavenge</name>
		<tag>jmxsensor,mjjmxsensor</tag>
		<kind>mjjmxgcpssensor</kind>
		<description>PS Scavenge Garbage Collection statistics</description>
		<baseclass>com.paessler.prtg.jmx.sensors.JMXSensor</baseclass>
		<help>JVM PS Scavenge Garbage Collection metrics</help>
		<entries>
			<entry>
				<object>java.lang:type=GarbageCollector,name=PS Scavenge</object>
				<displayvalue>PS GarbageCollector Stats</displayvalue>
				<description>PS Scavenge Garbage Collector</description>
				<shortdescription>GC-PS</shortdescription>
				<comment>Class Name:sun.management.GarbageCollectorImpl</comment>
				<attributes>
					<attribute>
						<object>CollectionCount</object>
						<displayvalue/>
						<description>CollectionCount</description>
						<shortdescription/>
						<comment>type=long,unit=COUNT; Value=0</comment>
						<unit/>
						<customunit/>
						<enabled>true</enabled>
					</attribute>
					<attribute>
						<object>CollectionTime</object>
						<displayvalue/>
						<description>CollectionTime</description>
						<shortdescription/>
						<comment>type=long,unit=COUNT; Value=0</comment>
						<unit/>
						<customunit/>
						<enabled>true</enabled>
					</attribute>
					<attribute>
						<object>LastGcInfo</object>
						<displayvalue/>
						<description>LastGcInfo</description>
						<shortdescription/>
						<comment>type=javax.management.openmbean.CompositeData,unit=COUNT</comment>
						<unit/>
						<customunit/>
						<enabled>true</enabled>
					</attribute>
					<attribute>
						<object>MemoryPoolNames</object>
						<displayvalue/>
						<description>MemoryPoolNames</description>
						<shortdescription/>
						<comment>type=[Ljava.lang.String;,unit=COUNT; Value=[Ljava.lang.String;@417cc8df</comment>
						<unit/>
						<customunit/>
						<enabled>true</enabled>
					</attribute>
					<attribute>
						<object>Name</object>
						<displayvalue/>
						<description>Name</description>
						<shortdescription/>
						<comment>type=java.lang.String,unit=COUNT; Value=PS Scavenge</comment>
						<unit/>
						<customunit/>
						<enabled>true</enabled>
					</attribute>
					<attribute>
						<object>ObjectName</object>
						<displayvalue/>
						<description>ObjectName</description>
						<shortdescription/>
						<comment>type=javax.management.ObjectName,unit=COUNT; Value=java.lang:type=GarbageCollector,name=PS Scavenge</comment>
						<unit/>
						<customunit/>
						<enabled>true</enabled>
					</attribute>
					<attribute>
						<object>Valid</object>
						<displayvalue/>
						<description>Valid</description>
						<shortdescription/>
						<comment>type=boolean,unit=COUNT; Value=true</comment>
						<unit/>
						<customunit/>
						<enabled>true</enabled>
					</attribute>
				</attributes>
			</entry>
		</entries>
	</profile>
</profiles>

=== PRTG/JMXMiniProbe/profiles/PortSensors.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- ###########################################################
Unit Values[BANDWIDTH, MEMORY, DISK, FILE, TIME_RESPONSE, TIME_SECONDS, TIME_HOURS, TEMP, PERCENT, COUNT,CPU,CUSTOM]
***************************************************************
 This file contains the definition of the PRTG JMXMiniProbe MBean
*** PLEASE DO NOT MODIFY ***
Please note, the apache.commons.digester3 is * VERY * case sensitive
########################################################### -->
<profiles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Profile.xsd">
	<profile>
		<name>Ports AD Critical 5</name>
		<kind>adcritical5portssensor</kind>
		<tag>jmxsensor,mjportrangesensor</tag>
		<description>Active directory Critical 5[389,88,53,445,464] ports</description>
		<baseclass>com.paessler.prtg.jmx.sensors.port.PortSensor</baseclass>
		<help>Monitors the critical 5 ports for Active Directory [ldap(389),kerberos(88),DNS(53),microsoft-ds(445),kpasswd(464)]</help>
		<entries>
      <entry>
        <object>AD Critical Ports</object>
        <displayvalue>AD Critical 5</displayvalue>
        <description>AD: Critical Ports</description>
        <shortdescription>MSAD</shortdescription>
        <help>Monitoring ports ldap[389],kerberos[88],DNS[53],microsoft-ds[445],kpasswd[464]</help>
        <attributes>
          <attribute>
            <object>389</object>
            <displayvalue>AD Critical ldap[89]</displayvalue>
            <description>AD Critical ldap[389]</description>
            <shortdescription/>
            <comment>type=java.lang.long</comment>
            <unit>TimeResponse</unit>
            <limitmode>1</limitmode>
            <limitmaxerror>100</limitmaxerror>
            <limitmaxwarning>75</limitmaxwarning>
            <limiterrormsg>AD Critical ldap[389] responses approaching unacceptable level</limiterrormsg>
            <limitwarningmsg>AD Critical ldap[389] responses at unacceptable level</limitwarningmsg>
          </attribute>
          <attribute>
            <object>88</object>
            <displayvalue>AD Critical kerberos[88]</displayvalue>
            <description>AD Critical kerberos[88]</description>
            <shortdescription/>
            <comment>type=java.lang.long</comment>
            <unit>TimeResponse</unit>
            <limitmaxerror>100</limitmaxerror>
            <limitmaxwarning>75</limitmaxwarning>
            <limiterrormsg>AD Critical kerberos[88] responses approaching unacceptable level</limiterrormsg>
            <limitwarningmsg>AD Critical kerberos[88] responses at unacceptable level</limitwarningmsg>
          </attribute>
          <attribute>
            <object>53</object>
            <displayvalue>AD Critical dns[53]</displayvalue>
            <description>AD Critical dns[53]</description>
            <shortdescription/>
            <comment>type=java.lang.long</comment>
            <unit>TimeResponse</unit>
            <limitmaxerror>100</limitmaxerror>
            <limitmaxwarning>75</limitmaxwarning>
            <limiterrormsg>AD Critical dns[53] responses approaching unacceptable level</limiterrormsg>
            <limitwarningmsg>AD Critical dns[53] responses at unacceptable level</limitwarningmsg>
          </attribute>
          <attribute>
            <object>445</object>
            <displayvalue>AD Critical microsoft-ds[445]</displayvalue>
            <description>AD Critical microsoft-ds[445]</description>
            <shortdescription/>
            <comment>type=java.lang.long</comment>
            <unit>TimeResponse</unit>
            <limitmaxerror>100</limitmaxerror>
            <limitmaxwarning>75</limitmaxwarning>
            <limiterrormsg>AD Critical microsoft-ds[445] responses approaching unacceptable level</limiterrormsg>
            <limitwarningmsg>AD Critical microsoft-ds[445] responses at unacceptable level</limitwarningmsg>
          </attribute>
          <attribute>
            <object>464</object>
            <displayvalue>AD Critical kpasswd[464]</displayvalue>
            <description>AD Critical kpasswd[464]</description>
            <shortdescription/>
            <comment>type=java.lang.long</comment>
            <unit>TimeResponse</unit>
            <limitmaxerror>100</limitmaxerror>
            <limitmaxwarning>75</limitmaxwarning>
            <limiterrormsg>AD Critical kpasswd[464] responses approaching unacceptable level</limiterrormsg>
            <limitwarningmsg>AD Critical kpasswd[464] responses at unacceptable level</limitwarningmsg>
          </attribute>
        </attributes>
      </entry>
		</entries>
	</profile>
	
</profiles>
