=== PRTG/JMXMiniProbe/profiles/Profile.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="profiles">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="profile" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="kind" minOccurs="1">
				<xs:annotation>
					<xs:documentation>Unique Identifier for the sensor(should start with 'mjjmx*'")</xs:documentation>
				</xs:annotation>
			   </xs:element>
              <xs:element type="xs:string" name="name" minOccurs="1">
				<xs:annotation>
					<xs:documentation>Name of the sensor. Will become the default name</xs:documentation>
				</xs:annotation>
			   </xs:element>
              <xs:element type="xs:string" name="tag" minOccurs="1">
				<xs:annotation>
					<xs:documentation>Tags values. Should include the tag of the parrent</xs:documentation>
				</xs:annotation>
			   </xs:element>
              <xs:element type="xs:string" name="description" minOccurs="0">
				<xs:annotation>
					<xs:documentation>What is displayed in the description in the Add Sensor Dialog</xs:documentation>
				</xs:annotation>
			   </xs:element>
              <!--xs:element type="xs:string" name="baseclass" minOccurs="1"/-->
			  <xs:element name="baseclass" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>The class that implements the sensor used</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
				  <xs:restriction base="xs:string">
					<!-- Tags: jmxsensor,mjjmxsensor -->
					<xs:enumeration value="com.paessler.prtg.jmx.sensors.JMXSensor"/>
					<!-- Tags: jmxsensor,mjjmxsensor -->
					<xs:enumeration value="com.paessler.prtg.jmx.sensors.port.PortSensor"/>
				  </xs:restriction>
				</xs:simpleType>
			  </xs:element>
              <xs:element type="xs:string" name="help"/>
              <!-- Properties -->
			  <xs:element name="properties" minOccurs="0">
				<xs:complexType>
				  <xs:sequence>
					<xs:element name="property" type="PropertyType"/>
				  </xs:sequence>
				</xs:complexType>
			  </xs:element>
              <!-- Properties -->
              <!-- Please note, the total number of Attributes for all the entries in a Profile, 
			  is limited to PRTG Channels per Sensor -->
              <xs:element name="entries">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="entry">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="object" minOccurs="1">
							<xs:annotation>
								<xs:documentation>Name of Entry</xs:documentation>
							</xs:annotation>
						  </xs:element>
                          <xs:element type="xs:string" name="displayvalue" minOccurs="0">
							<xs:annotation>
								<xs:documentation>Value to be displayed</xs:documentation>
							</xs:annotation>
						  </xs:element>
                          <xs:element type="xs:string" name="description" minOccurs="0">
							<xs:annotation>
								<xs:documentation>Description of entry</xs:documentation>
							</xs:annotation>
						  </xs:element>
                          <xs:element type="xs:string" name="shortdescription" minOccurs="0">
							<xs:annotation>
								<xs:documentation>Short description, will be used to indicate entry for a Channel</xs:documentation>
							</xs:annotation>
						  </xs:element>
                          <xs:element type="xs:string" name="comment" minOccurs="0">
							<xs:annotation>
								<xs:documentation>Arbitrary comment</xs:documentation>
							</xs:annotation>
						  </xs:element>
              			<!-- Properties -->
						<xs:element name="properties" minOccurs="0">
							<xs:complexType>
							  <xs:sequence>
								<xs:element name="property" type="PropertyType"/>
							  </xs:sequence>
							</xs:complexType>
						</xs:element>
              			<!-- Properties -->
                          <xs:element name="attributes" minOccurs="1" maxOccurs="50">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="attribute">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element type="xs:string" name="object" minOccurs="1"/>
                                      <xs:element type="xs:string" name="displayvalue" minOccurs="0"/>
                                      <xs:element type="xs:string" name="description" minOccurs="0"/>
                                      <xs:element type="xs:string" name="shortdescription" minOccurs="0"/>
                                      <xs:element type="xs:string" name="comment" minOccurs="0"/>
                                      <xs:element name="unit" minOccurs="1">
										<xs:annotation>
											<xs:documentation>Valid Units for PRTG</xs:documentation>
										</xs:annotation>
								        <xs:simpleType>
								          <xs:restriction base="xs:string">
										    <xs:enumeration value="BANDWIDTH"/>		<!-- BytesBandwidth -->
										    <xs:enumeration value="MEMORY"/>		<!-- BytesMemory -->
										    <xs:enumeration value="DISK"/>			<!-- BytesDisk -->
										    <xs:enumeration value="FILE"/>			<!-- BytesFile -->
										    <xs:enumeration value="TIME_RESPONSE"/>	<!-- TimeResponse[ms] -->
										    <xs:enumeration value="TIME_SECONDS"/>	<!-- TimeSeconds -->
										    <xs:enumeration value="TIME_HOURS"/>	<!-- TimeHours -->
										    <xs:enumeration value="TEMP"/>			<!-- Temperature -->
										    <xs:enumeration value="PERCENT"/>		<!-- Percent -->
										    <xs:enumeration value="COUNT"/>			<!-- Count -->
										    <xs:enumeration value="CPU"/>  			<!-- CPU (*) -->
										    <xs:enumeration value="CUSTOM"/>		<!-- Custom (define the name of the unit using the additional field customunit) -->
								          </xs:restriction>
								        </xs:simpleType>
                                      </xs:element>
                                      <xs:element type="xs:string" name="customunit" minOccurs="0"/>
                                      <xs:element type="xs:boolean" name="enabled" minOccurs="0"/>
                                      <xs:element type="xs:float" name="mpy" default="1.0" minOccurs="0"/>
                                      <xs:element type="xs:float" name="div" default="1.0" minOccurs="0"/>
                                      <xs:element type="xs:int" name="limitmaxerror" minOccurs="0"/>
                                      <xs:element type="xs:int" name="limitmaxwarning" minOccurs="0"/>
                                      <xs:element type="xs:int" name="limitminwarning" minOccurs="0"/>
                                      <xs:element type="xs:int" name="limitminerror" minOccurs="0"/>
                                      <xs:element type="xs:string" name="limiterrormsg" minOccurs="0"/>
                                      <xs:element type="xs:string" name="limitwarningmsg" minOccurs="0"/>
                                      <xs:element type="xs:int" name="limitmode" default="0" minOccurs="0"/>
                                      <xs:element name="properties" minOccurs="0">
                                        <xs:complexType>
                                          <xs:sequence>
											<xs:element name="property" type="PropertyType"/>
                                          </xs:sequence>
                                        </xs:complexType>
                                      </xs:element>
                                      <!-- Properties -->
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <!-- Attribute -->
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <!-- Attributes -->
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <!-- Element -->
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <!-- Profile -->
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- Profiles -->
  
	<!-- Name Value Pairs-->
    <xs:complexType name="NameValuePairsType">
		<xs:annotation>
			<xs:documentation>Arbitrary name value pair</xs:documentation>
		</xs:annotation>
		<xs:sequence>
		  <xs:element type="xs:string" name="name">
			<xs:annotation>
				<xs:documentation>Property name</xs:documentation>
			</xs:annotation>
		   </xs:element>
		  <xs:element type="xs:string" name="value">
			<xs:annotation>
				<xs:documentation>Property value</xs:documentation>
			</xs:annotation>
		   </xs:element>
		</xs:sequence>
	</xs:complexType>
	<!-- Name Value Pairs-->
	<!-- Property-->
    <xs:complexType name="PropertyType">
		<xs:annotation>
			<xs:documentation>Sequence of name value pair</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="property" type="NameValuePairsType"/>
		</xs:sequence>
	</xs:complexType>
	

<!--
                          <xs:element name="properties">
                            <xs:complexType>
                              <xs:sequence>
								<xs:element name="property">
									<xs:annotation>
										<xs:documentation>Arbitrary attribute to be set on the sensor</xs:documentation>
									</xs:annotation>
								  <xs:complexType>
									<xs:sequence>
									  <xs:element type="xs:string" name="name">
										<xs:annotation>
											<xs:documentation>Property name</xs:documentation>
										</xs:annotation>
									   </xs:element>
									  <xs:element type="xs:string" name="value">
										<xs:annotation>
											<xs:documentation>Property value</xs:documentation>
										</xs:annotation>
									   </xs:element>
									</xs:sequence>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
 -->	
</xs:schema>

=== PRTG/JMXMiniProbe/profiles/SNMP-GTT.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- ###########################################################
Unit Values[BANDWIDTH, MEMORY, DISK, FILE, TIME_RESPONSE, TIME_SECONDS, TIME_HOURS, TEMP, PERCENT, COUNT,CPU,CUSTOM]
***************************************************************
 This file contains the definition of the PRTG JMXMiniProbe MBean
*** PLEASE DO NOT MODIFY ***
Please note, the apache.commons.digester3 is * VERY * case sensitive
########################################################### -->
<profiles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Profile.xsd">
	<profile>
		<name>SNMP Custom OID Test</name>
		<kind>mjgttcustomsnmpsensor</kind>
		<tag>mjmxsensor,mjportrangesensor</tag>
		<description>Test of Custom OIDs Profile</description>
		<baseclass>com.paessler.prtg.jmx.sensors.SNMPSensor</baseclass>
		<help>Monitors a list of OIDs </help>
		<entries>
      <entry>
        <object>Custom SNMP Object</object>
        <displayvalue>Custom SNMP Display</displayvalue>
        <description>SNMP: Custom</description>
        <shortdescription>SNMP:Junk</shortdescription>
        <help>Custom SNMP Obj, Help</help>
        <attributes>
          <attribute>
            <object>1.3.6.1.4.1.9.9.109.1.1.1.1.10</object>
            <displayvalue>CPU TotMonInt Busy</displayvalue>
            <description>CPU TotMonInt Busy indicator</description>
            <shortdescription/>
            <comment>type=java.lang.int</comment>
			<!--unit>{BANDWIDTH|MEMORY|DISK|FILE|TIME_RESPONSE|TIME_SECONDS|TIME_HOURS|TEMP|PERCENT|COUNT|CPU|CUSTOM}</unit-->
            <unit>CPU</unit>
			<!--customunit>Custom Unit name like "Unicorns"</customunit>
			<enabled>true</enabled>
			<mpy>1.0</mpy>
			<div>1.0</div-->
            <limitmode>1</limitmode>
            <limitmaxerror>95</limitmaxerror>
            <limitmaxwarning>75</limitmaxwarning>
            <limiterrormsg>CPU 1min at unacceptable level</limiterrormsg>
            <limitwarningmsg>CPU 1min approaching unacceptable level</limitwarningmsg>
          </attribute>
          <attribute>
            <object>1.3.6.1.4.1.9.9.109.1.1.1.1.6</object>
            <displayvalue>CPU 5sec Busy</displayvalue>
            <description>CPU 5/Sec Busy indicator</description>
            <shortdescription/>
            <comment>type=java.lang.int</comment>
            <unit>CPU</unit>
            <limitmode>1</limitmode>
            <limitmaxerror>95</limitmaxerror>
            <limitmaxwarning>75</limitmaxwarning>
            <limiterrormsg>CPU 5/sec at unacceptable level</limiterrormsg>
            <limitwarningmsg>CPU 5/sec approaching unacceptable level</limitwarningmsg>
          </attribute>
          <attribute>
            <object>1.3.6.1.4.1.9.9.109.1.1.1.1.7</object>
            <displayvalue>CPU 1min Busy</displayvalue>
            <description>CPU 1min Busy indicator</description>
            <shortdescription/>
            <comment>type=java.lang.int</comment>
            <unit>CPU</unit>
            <limitmode>1</limitmode>
            <limitmaxerror>95</limitmaxerror>
            <limitmaxwarning>75</limitmaxwarning>
            <limiterrormsg>CPU 1min at unacceptable level</limiterrormsg>
            <limitwarningmsg>CPU 1min approaching unacceptable level</limitwarningmsg>
          </attribute>
        </attributes>
      </entry>
		</entries>
	</profile>
	
</profiles>

=== PRTG/JMXMiniProbe/profiles/CiscoProfile.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- ###########################################################
Unit Values[BANDWIDTH, MEMORY, DISK, FILE, TIME_RESPONSE, TIME_SECONDS, TIME_HOURS, TEMP, PERCENT, COUNT,CPU,CUSTOM]
***************************************************************
 This file contains the definition of the PRTG JMXMiniProbe MBean
*** PLEASE DO NOT MODIFY ***
Please note, the apache.commons.digester3 is * VERY * case sensitive
########################################################### -->
<profiles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Profile.xsd">
	<profile>
		<name>Profile: Cisco CPU Busy[Old]</name>
		<kind>mjsnmpciscocpu1203sensor</kind>
		<tag>mjmxsensor,mjsnmpesensor</tag>
		<description>Cisco CPU IOS [12.0.3]</description>
		<baseclass>com.paessler.prtg.jmx.sensors.SNMPSensor</baseclass>
		<help>Monitors CISCO CPU Busy OIDs[pre ios 12.0.3] </help>
		<entries>
      <entry>
        <object>Custom SNMP Object</object>
        <displayvalue>Custom SNMP Display</displayvalue>
        <description>SNMP: Custom</description>
        <shortdescription>SNMP:Junk</shortdescription>
        <help>Custom SNMP Obj, Help</help>
        <attributes>
          <attribute>
            <object>1.3.6.1.4.1.9.2.1.58.0</object>
            <displayvalue>CPU TotMonInt Busy</displayvalue>
            <description>CPU TotMonInt Busy indicator</description>
            <shortdescription/>
            <comment>type=java.lang.int</comment>
			<!--unit>{BANDWIDTH|MEMORY|DISK|FILE|TIME_RESPONSE|TIME_SECONDS|TIME_HOURS|TEMP|PERCENT|COUNT|CPU|CUSTOM}</unit-->
            <unit>CPU</unit>
			<!--customunit>Custom Unit name like "Unicorns"</customunit>
			<enabled>true</enabled>
			<mpy>1.0</mpy>
			<div>1.0</div-->
            <limitmode>1</limitmode>
            <limitmaxerror>95</limitmaxerror>
            <limitmaxwarning>75</limitmaxwarning>
            <limiterrormsg>CPU 1min at unacceptable level</limiterrormsg>
            <limitwarningmsg>CPU 1min approaching unacceptable level</limitwarningmsg>
          </attribute>
          <attribute>
            <object>1.3.6.1.4.1.9.2.1.56.0</object>
            <displayvalue>CPU 5sec Busy</displayvalue>
            <description>CPU 5/Sec Busy indicator</description>
            <shortdescription/>
            <comment>type=java.lang.int</comment>
            <unit>CPU</unit>
            <limitmode>1</limitmode>
            <limitmaxerror>95</limitmaxerror>
            <limitmaxwarning>75</limitmaxwarning>
            <limiterrormsg>CPU 5/sec at unacceptable level</limiterrormsg>
            <limitwarningmsg>CPU 5/sec approaching unacceptable level</limitwarningmsg>
          </attribute>
          <attribute>
            <object>1.3.6.1.4.1.9.2.1.57.0</object>
            <displayvalue>CPU 1min Busy</displayvalue>
            <description>CPU 1min Busy indicator</description>
            <shortdescription/>
            <comment>type=java.lang.int</comment>
            <unit>CPU</unit>
            <limitmode>1</limitmode>
            <limitmaxerror>95</limitmaxerror>
            <limitmaxwarning>75</limitmaxwarning>
            <limiterrormsg>CPU 1min at unacceptable level</limiterrormsg>
            <limitwarningmsg>CPU 1min approaching unacceptable level</limitwarningmsg>
          </attribute>
        </attributes>
      </entry>
		</entries>
	</profile>
	<!-- ************************************* -->
	<profile>
		<name>Profile: Cisco CPU Busy[12.0.3-5]</name>
		<kind>mjsnmpciscocpuold1205sensor</kind>
		<tag>mjmxsensor,mjsnmpesensor</tag>
		<description>Cisco CPU IOS [12.0.3-5]</description>
		<baseclass>com.paessler.prtg.jmx.sensors.SNMPSensor</baseclass>
		<help>Monitors CISCO CPU Busy OIDs[ios 12.0.3 - 12.2.5] </help>
		<entries>
      <entry>
        <object>Custom SNMP Object</object>
        <displayvalue>Custom SNMP Display</displayvalue>
        <description>SNMP: Custom</description>
        <shortdescription>SNMP:Junk</shortdescription>
        <help>Custom SNMP Obj, Help</help>
        <attributes>
          <attribute>
            <object>1.3.6.1.4.1.9.9.109.1.1.1.1.4.0</object>
            <displayvalue>CPU Tot 1min Busy</displayvalue>
            <description>CPU cpmCPUTotal1min Busy indicator</description>
            <shortdescription/>
            <comment>type=java.lang.int</comment>
			<!--unit>{BANDWIDTH|MEMORY|DISK|FILE|TIME_RESPONSE|TIME_SECONDS|TIME_HOURS|TEMP|PERCENT|COUNT|CPU|CUSTOM}</unit-->
            <unit>CPU</unit>
			<!--customunit>Custom Unit name like "Unicorns"</customunit>
			<enabled>true</enabled>
			<mpy>1.0</mpy>
			<div>1.0</div-->
            <limitmode>1</limitmode>
            <limitmaxerror>95</limitmaxerror>
            <limitmaxwarning>75</limitmaxwarning>
            <limiterrormsg>CPU 1min at unacceptable level</limiterrormsg>
            <limitwarningmsg>CPU 1min approaching unacceptable level</limitwarningmsg>
          </attribute>
          <attribute>
            <object>1.3.6.1.4.1.9.9.109.1.1.1.1.3.0</object>
            <displayvalue>CPU 5sec Busy</displayvalue>
            <description>CPU 5/Sec Busy indicator</description>
            <shortdescription/>
            <comment>type=java.lang.int</comment>
            <unit>CPU</unit>
            <limitmode>1</limitmode>
            <limitmaxerror>95</limitmaxerror>
            <limitmaxwarning>75</limitmaxwarning>
            <limiterrormsg>CPU 5/sec at unacceptable level</limiterrormsg>
            <limitwarningmsg>CPU 5/sec approaching unacceptable level</limitwarningmsg>
          </attribute>
          <attribute>
            <object>1.3.6.1.4.1.9.9.109.1.1.1.1.5.0</object>
            <displayvalue>CPU 5min Busy</displayvalue>
            <description>CPU 5min Busy indicator</description>
            <shortdescription/>
            <comment>type=java.lang.int</comment>
            <unit>CPU</unit>
            <limitmode>1</limitmode>
            <limitmaxerror>95</limitmaxerror>
            <limitmaxwarning>75</limitmaxwarning>
            <limiterrormsg>CPU 5min at unacceptable level</limiterrormsg>
            <limitwarningmsg>CPU 5min approaching unacceptable level</limitwarningmsg>
          </attribute>
        </attributes>
      </entry>
		</entries>
	</profile>
	<!-- ************************************* -->
	<profile>
		<name>Profile: Cisco CPU Busy [12.2(3.5)+]</name>
		<kind>mjsnmpciscocpu12235sensor</kind>
		<tag>mjmxsensor,mjsnmpesensor</tag>
		<description>Test of Custom OIDs Profile</description>
		<baseclass>com.paessler.prtg.jmx.sensors.SNMPSensor</baseclass>
		<help>Monitors CISCO CPU Busy OIDs[ios 12.2(3.5)] </help>
		<entries>
      <entry>
        <object>Custom SNMP Object</object>
        <displayvalue>Custom SNMP Display</displayvalue>
        <description>SNMP: Custom</description>
        <shortdescription>SNMP:Junk</shortdescription>
        <help>Custom SNMP Obj, Help</help>
        <attributes>
          <attribute>
            <object>1.3.6.1.4.1.9.9.109.1.1.1.1.7.0</object>
            <displayvalue>CPU Tot 1min Busy</displayvalue>
            <description>CPU cpmCPUTotal1min Busy indicator</description>
            <shortdescription/>
            <comment>type=java.lang.int</comment>
			<!--unit>{BANDWIDTH|MEMORY|DISK|FILE|TIME_RESPONSE|TIME_SECONDS|TIME_HOURS|TEMP|PERCENT|COUNT|CPU|CUSTOM}</unit-->
            <unit>CPU</unit>
			<!--customunit>Custom Unit name like "Unicorns"</customunit>
			<enabled>true</enabled>
			<mpy>1.0</mpy>
			<div>1.0</div-->
            <limitmode>1</limitmode>
            <limitmaxerror>95</limitmaxerror>
            <limitmaxwarning>75</limitmaxwarning>
            <limiterrormsg>CPU 1min at unacceptable level</limiterrormsg>
            <limitwarningmsg>CPU 1min approaching unacceptable level</limitwarningmsg>
          </attribute>
          <attribute>
            <object>1.3.6.1.4.1.9.9.109.1.1.1.1.6.0</object>
            <displayvalue>CPU 5sec Busy</displayvalue>
            <description>CPU 5/Sec Busy indicator</description>
            <shortdescription/>
            <comment>type=java.lang.int</comment>
            <unit>CPU</unit>
            <limitmode>1</limitmode>
            <limitmaxerror>95</limitmaxerror>
            <limitmaxwarning>75</limitmaxwarning>
            <limiterrormsg>CPU 5/sec at unacceptable level</limiterrormsg>
            <limitwarningmsg>CPU 5/sec approaching unacceptable level</limitwarningmsg>
          </attribute>
          <attribute>
            <object>1.3.6.1.4.1.9.9.109.1.1.1.1.8.0</object>
            <displayvalue>CPU 5min Busy</displayvalue>
            <description>CPU 5min Busy indicator</description>
            <shortdescription/>
            <comment>type=java.lang.int</comment>
            <unit>CPU</unit>
            <limitmode>1</limitmode>
            <limitmaxerror>95</limitmaxerror>
            <limitmaxwarning>75</limitmaxwarning>
            <limiterrormsg>CPU 5min at unacceptable level</limiterrormsg>
            <limitwarningmsg>CPU 5min approaching unacceptable level</limitwarningmsg>
          </attribute>
        </attributes>
      </entry>
		</entries>
	</profile>
	
</profiles>

=== PRTG/JMXMiniProbe/profiles/JMXMiniProbe.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- ###########################################################
Unit Values[BANDWIDTH, MEMORY, DISK, FILE, TIME_RESPONSE, TIME_SECONDS, TIME_HOURS, TEMP, PERCENT, COUNT,CPU,CUSTOM]
***************************************************************
 This file contains the definition of the PRTG JMXMiniProbe MBean
*** PLEASE DO NOT MODIFY ***
Please note, the apache.commons.digester3 is * VERY * case sensitive
########################################################### -->
<profiles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Profile.xsd">
	<profile>
		<kind>jmxmpsensor</kind>
		<name>JMX MiniProbe Metrics</name>
		<tag>jmxsensor,mjjmxsensor</tag>
		<description>PRTG JMXMiniProbe metrics</description>
		<baseclass>com.paessler.prtg.jmx.sensors.JMXSensor</baseclass>
		<help>Performance metrics for the probe itself</help>
		<entries>
		  <entry>
			<object>com.paessler.prtg.jmx.mbean.PRTGBean:name=JMXMiniProbe</object>
			<displayvalue/>
			<description>JMX: PRTG JMXMiniProbe statistics</description>
			<shortdescription>PRTG</shortdescription>
			<comment>Class Name:com.paessler.prtg.jmx.mbean.PRTGInterface</comment>
			<attributes>
			  <attribute>
				<object>AvgExecutionTime</object>
				<displayvalue>Avg Sensor Exec</displayvalue>
				<description>AvgExecutionTime, Average query Execution.</description>
				<shortdescription/>
				<comment>type=java.lang.long</comment>
				<unit>TIME_RESPONSE</unit>
			  </attribute>
			  <attribute>
				<object>AvgSenorCreationTime</object>
				<displayvalue>Avg Sensor Creation</displayvalue>
				<description>AvgSenorCreationTime, Average sensor creation.</description>
				<shortdescription/>
				<comment>type=java.lang.long</comment>
				<unit>TIME_RESPONSE</unit>
			  </attribute>
			  <attribute>
				<object>AvgUploadTime</object>
				<displayvalue>Avg Upload</displayvalue>
				<description>avgUploadTime, Average time to upload data.</description>
				<shortdescription/>
				<comment>type=java.lang.long</comment>
				<unit>TIME_RESPONSE</unit>
			  </attribute>
			  <attribute>
				<object>QueryCount</object>
				<displayvalue>Number of Poll iterations</displayvalue>
				<description>QueryCount, Poll iterations performed.</description>
				<shortdescription/>
				<comment>type=java.lang.long</comment>
				<unit>COUNT</unit>
			  </attribute>
			  <attribute>
				<object>SensorCount</object>
				<displayvalue>Number of Sensors</displayvalue>
				<description>SensorCount, Number of sensors.</description>
				<shortdescription/>
				<comment>type=java.lang.int</comment>
				<unit>COUNT</unit>
			  </attribute>
			</attributes>
		  </entry>
		</entries>
	</profile>
	
</profiles>
